export * from './home';
export * from './profile';
export * from './skillCard';
export * from './modal';
export * from './login';
export * from './register';
export * from './protectedRoute';
export * from './not-fount-404';
export * from './server-error-500';
